feat: include coverage message
VeryGoodOpenSource/very_good_coverage pull request #159
Opened 2022-07-20 19:32 UTC by alestiago

## Description

Automatically adds a comment to the pull request with coverage information. If a comment already exists it automatically updates the comment with the new information to avoid polluting the conversation history.

Includes two new parameters:
- `report_coverage_comment` which reports coverage information as a pull request comment.
- `github_token` token required to comment on a pull request.

Aims to resolve #101 .

## Comment formats

Successful comment looks like:

## ✅ VeryGoodCoverage
Coverage: 100% (100 of 100 lines)
Min coverage difference: 0% (100% / 100%)

Unsuccessful comment looks like:

## ❌ VeryGoodCoverage
Coverage: 95% (95 of 100 lines)
Min coverage difference: 5-1% (95% / 9096%)

<details>
<summary> Lines not covered </summary>
- /Users/felix/Development/github.com/felangel/bloc/packages/bloc/lib/src/bloc_observer.dart: 20, 27, 36, 43, 51
</details>
## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2022-07-20 19:37 UTC, felangel requested changes
Can we add tests for the changes?

2022-07-20 19:38 UTC, alestiago commented
> https://github.com/VeryGoodOpenSource/very_good_coverage/pull/159#pullrequestreview-1045580742

Are we happy with the above comment formats?

2023-01-26 15:33 UTC, alestiago reviewed
Refactored code as said in the previous comment. Designed unit tests for the new added functions. 

Missing an integration test that checks the run method acts as expected. Needs further discussion to wether we want to test with a real endpoint or we want to fully mock.

(cc: @felangel )

2023-01-26 15:33 UTC, alestiago commented on index.test.js
> +test('formatCoverageAsMessage returns normally', () => {
More test can be added to verify the formatting is correct. I'll wait until an agreed format is decided.

2023-01-26 15:33 UTC, alestiago commented on index.test.js
> +  // expect(createComment).toHaveBeenCalled();
@felangel 👀

2023-09-19 10:42 UTC, closed without merging